apiVersion: v1
kind: ConfigMap
metadata:
  name: react-cicd-app-config
  labels:
    app: react-cicd-app
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        gzip on;
        gzip_types text/css application/javascript text/javascript application/json;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }

  app.env: |
    REACT_APP_ENV=production
    REACT_APP_VERSION=1.0.0
