apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cicd-app
  labels:
    app: react-cicd-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:   # ✅ fixed typo "matchLables"
      app: react-cicd-app
  template:
    metadata:
      labels:
        app: react-cicd-app
        version: v1
    spec:
      containers:
        - name: react-cicd-app
          image: abhishekbhatt0/react-cicd-app:latest
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30   # ✅ fixed typo initiaDelaySeconds
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5    # ✅ fixed typo
            periodSeconds: 5
          env:
            - name: NODE_ENV
              value: "production"
